CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_PM_SOFT_OFF=y

# 启用电池电量报告
CONFIG_ZMK_BATTERY_REPORTING=y
# 延长电量刷新间隔（分钟），避免频繁唤醒副端导致额外耗电
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# 启用副端电量传输
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
